name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install Dependencies
        run: |
          sudo npm install -g newman
          sudo npm install -g newman-reporter-htmlextra
          sudo npm install -g newman-reporter-allure
          
      - name: Create Reports Directory
        run: |
          mkdir -p newman
          mkdir -p allure-results
          
      - name: List Directory Contents
        run: |
          pwd
          ls -la
          ls -la postman/
          
      - name: Run Postman Collection
        run: |
          newman run "postman/collection.json" \
          -e "postman/environment.json" \
          -r htmlextra,allure \
          --reporter-htmlextra-export "newman/htmlreport.html" \
          --reporter-allure-export "allure-results"
          
      - name: Store Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            newman/
            allure-results/