name: Postman API Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Newman and Reporters
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure
          newman --version
      
      - name: Install Allure CommandLine
        run: |
          curl -o allure-2.24.1.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
          allure --version
      
      - name: Setup Directories
        run: |
          rm -rf newman allure-results allure-report
          mkdir -p newman
          mkdir -p allure-results
      
      - name: Run Newman Tests
        continue-on-error: true
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,htmlextra,allure \
          --reporter-htmlextra-export="newman/report.html" \
          --reporter-allure-export="allure-results" \
          --suppress-exit-code
      
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            newman/
            allure-results/
            allure-report/
          retention-days: 30