name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Newman and Reporter
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra
          newman --version
      
      - name: Create Reports Directory
        run: mkdir -p newman
      
      - name: Run Newman Tests
        continue-on-error: true  # Permite continuar aunque haya fallos en las pruebas
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export="newman/report.html" \
          --suppress-exit-code
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-results
          path: newman/
          retention-days: 30