name: Postman API Tests
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
         
      - name: Install Newman and Reporters
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure
          newman --version
     
      - name: Clean and Create Directories
        run: |
          rm -rf newman allure-results allure-report || true
          sleep 1
          mkdir -p newman
          mkdir -p allure-results
          chmod 777 newman allure-results
     
      - name: Install Allure CommandLine
        run: |
          wget -O allure-commandline.zip https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.zip
          unzip allure-commandline.zip -d /opt/
          sudo ln -sf /opt/allure-commandline-2.24.1/bin/allure /usr/bin/allure
          allure --version
     
      - name: Run Newman Tests
        continue-on-error: true
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,htmlextra,allure \
          --reporter-htmlextra-export="newman/report.html" \
          --reporter-allure-export="allure-results" \
          --suppress-exit-code
     
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report || true
     
      - name: Upload Newman Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/
          if-no-files-found: warn
     
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          if-no-files-found: warn