name: Postman API Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Newman and Reporters
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure
          newman --version
      
      - name: Setup Allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
      
      - name: Create Directories
        run: |
          mkdir -p newman
          mkdir -p allure-results
      
      - name: Run Newman Tests
        continue-on-error: true
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,htmlextra,allure \
          --reporter-htmlextra-export="newman/report.html" \
          --reporter-allure-export="allure-results" \
          --suppress-exit-code
      
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
      
      - name: Upload Newman Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-results
          path: newman/
          retention-days: 30
          
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: |
            allure-results
            allure-report
          retention-days: 30