name: Postman API Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
         
      - name: Install Newman and Reporters
        run: |
          sudo npm install -g newman@latest
          sudo npm install -g newman-reporter-htmlextra
          sudo npm install -g newman-reporter-allure
          newman --version

      - name: Clean and Create Directories
        run: |
          sudo rm -rf newman allure-results allure-report
          sleep 2
          sudo mkdir -p newman
          sudo mkdir -p allure-results
          sudo chmod -R 777 newman allure-results

          - name: Set up Allure
          run: |
            sudo apt-get update
            sudo apt-get install -y default-jre unzip
            wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
            sudo tar -zxvf allure-2.24.1.tgz -C /opt/
            sudo ln -sf /opt/allure-2.24.1/bin/allure /usr/bin/allure
            echo "Verifying Allure installation..."
            ls -la /opt/allure-2.24.1/bin/
            export PATH=$PATH:/opt/allure-2.24.1/bin
            allure --version

      - name: Run Newman Tests
        continue-on-error: true
        run: |
          echo "Running Newman tests..."
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,htmlextra,allure \
          --reporter-htmlextra-export="newman/report.html" \
          --reporter-allure-export="allure-results" \
          --suppress-exit-code
          echo "Listing generated files..."
          ls -la newman/ || true
          ls -la allure-results/ || true

          - name: Generate Allure Report
          if: always()
          run: |
            export PATH=$PATH:/opt/allure-2.24.1/bin
            echo "PATH=$PATH"
            echo "Checking Allure installation..."
            which allure || true
            echo "Listing allure-results directory..."
            ls -la allure-results || true
            echo "Generating Allure report..."
            allure generate allure-results --clean -o allure-report || echo "Failed to generate report"

      - name: Upload Newman Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/
          if-no-files-found: warn

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          if-no-files-found: warn